services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Scraping\ScraperCollection:
        arguments:
            -
                - '@App\Scraping\Scrapers\KiranicoItemScraper'
                - '@App\Scraping\Scrapers\KiranicoSkillsScraper'
                - '@App\Scraping\Scrapers\KiranicoCharmsScraper'
                - '@App\Scraping\Scrapers\FextralifeCharmRarityScraper'
                - '@App\Scraping\Scrapers\KiranicoWeaponsScraper'
                - '@App\Scraping\Scrapers\KiranicoArmorScraper'
                - '@App\Scraping\Scrapers\KiranicoDecorationsScraper'
                - '@App\Scraping\Scrapers\MHWikiaEldersealScraper'
                - '@App\Scraping\Scrapers\FextralifeArmorSetBonusScraper'
                - '@App\Scraping\Scrapers\CarlosFdezMHWorldDataDefenseValuesScraper'
                - '@App\Scraping\Scrapers\MHWikiaWeaponIconsScraper'

    App\Scraping\Configurations\KiranicoConfiguration: ~
    App\Scraping\Configurations\MHWikiaConfiguration: ~
    App\Scraping\Configurations\FextralifeConfiguration: ~
    App\Scraping\Configurations\GithubConfiguration: ~

    App\Scraping\Scrapers\KiranicoItemScraper: ~
    App\Scraping\Scrapers\KiranicoSkillsScraper: ~
    App\Scraping\Scrapers\KiranicoCharmsScraper: ~
    App\Scraping\Scrapers\FextralifeCharmRarityScraper: ~
    App\Scraping\Scrapers\KiranicoWeaponsScraper: ~
    App\Scraping\Scrapers\KiranicoArmorScraper: ~
    App\Scraping\Scrapers\KiranicoDecorationsScraper: ~
    App\Scraping\Scrapers\MHWikiaEldersealScraper: ~
    App\Scraping\Scrapers\FextralifeArmorSetBonusScraper: ~
    App\Scraping\Scrapers\CarlosFdezMHWorldDataDefenseValuesScraper: ~
    App\Scraping\Scrapers\MHWikiaWeaponIconsScraper: ~

    App\Scraping\Scrapers\Helpers\EldersealData:
        arguments:
            - '%kernel.root_dir%/Resources/data/missing-elderseal-values.json'