App\Entity\CharmRankCraftingInfo:
    type: entity
    table: charm_rank_crafting_info
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        craftable:
            type: boolean
            nullable: false
    manyToMany:
        materials:
            targetEntity: App\Entity\CraftingMaterialCost
            orphanRemoval: true
            cascade:
                - all
            joinTable:
                name: charm_rank_crafting_info_crafting_material_costs
                joinColumns:
                    charm_rank_id:
                        unique: true
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    crafting_material_cost_id:
                        nullable: false
                        options:
                            unsigned: true