App\Entity\CharmRank:
    type: entity
    table: charm_ranks
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
        level:
            type: smallint
            nullable: false
    manyToOne:
        charm:
            targetEntity: App\Entity\Charm
            inversedBy: ranks
            joinColumn:
                nullable: false
                options:
                    unsigned: true
    manyToMany:
        skills:
            targetEntity: App\Entity\SkillRank
            joinTable:
                name: charm_ranks_skill_ranks
                joinColumns:
                    charm_rank_id:
                        nullable: false
                        options:
                            unsigned: true
                inverseJoinColumns:
                    skill_rank_id:
                        nullable: false
                        options:
                            unsigned: true